# Generated by Django 5.2.17 on 2026-09-13 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone_preference', models.CharField(default='Warm', max_length=50)),
                ('communication_style', models.CharField(blank=True, max_length=255, null=True)),
                ('scenario_response', models.CharField(blank=True, max_length=255, null=True)),
                ('boundaries', models.CharField(blank=True, max_length=255, null=True)),
                ('psychological_answers', models.JSONField(blank=True, default=dict)),
                ('personality_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personality', to='accounts.googleuser')),
            ],
        ),
    ]
